name: Terraform Static Analysis Tests
description: Runs Terraform Static Analysis Tests - format, validate and plan

runs:
  using: "composite"
  steps:
    - name: Terraform Mock Route53 and ACM
      working-directory: route53Only
      shell: bash
      run: |
        terraform init
        terraform apply -auto-approve
        awslocal acm list-certificates

    - name: Terraform Validate and Plan
      shell: bash
      run: |
        awslocal acm list-certificates
        awslocal service-quotas get-service-quota --service-code apigateway --quota-code L-CDF5615A
        terraform init
        terraform fmt --recursive
        terraform validate
        terraform plan -lock=false -out terraform.plan
        terraform show -no-color terraform.plan > terraform.text

    - name: Report Terraform Plan
      uses: actions/github-script@v6
      with:
        script: |
          let stdout = '';
          let stderr = '';

          const options = {};
          options.listeners = {
            stdout: (data) => {
              stdout += data.toString();
            },
            stderr: (data) => {
              stderr += data.toString();
            }
          };
          await exec.exec('cat', ['terraform.text'], options);

          const output = `### Terraform Plan
          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${stdout}
          \`\`\`

          </details>`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
